apiVersion: v1
kind: Service
metadata:
  name: hello-world-service
spec:
  selector:
    app: hello-world
  ports:
    - protocol: TCP
      targetPort: 5000   # The port your app is running on inside the container
      port: 5000         # The port the service will expose
      nodePort: 30001    # The port that will be exposed on the node
  type: NodePort        # Exposes the service on a static port on the node

